### ISSUE TITLE
Fix the Floor of Back Bedroom

### ISSUE THREAD

**Issue by SuzyQuant** [United-Home/2405-45th-St#6]
### Problem: The floor of the bedroom sinks downwards and need some fixes to level the floor.

![image](https://user-images.githubusercontent.com/61100293/206005290-d32dbacf-2e48-4db1-903c-c765d9fcd0dc.jpeg)

![image](https://user-images.githubusercontent.com/61100293/206005331-0b83ee85-c59c-4dc6-9c55-059f10ae7971.jpeg)
---

### To Do for Contractors:
- [x] Asses the other things in the area that might fall down when working.
- [x] Take pictures **after** cutting and opening the floor.
- [ ] Write down your assessments in the comment section here.
- [x] Write down your Plan of Action. Include,

     - Materials to buy
     - All area that needs fixing
     - Estimated Time to finish

- [ ] Take action.
- [ ] Clean up.
- [ ] Upload in the comments area photos and write updates.
- [ ] Get paid with materials and labor costs. 

If the project is not done in one day, make sure to cover the working area so that no neighboring cats can get inside the house.

**Comment by SuzyQuant** [comment]
![image](https://user-images.githubusercontent.com/61100293/206577227-432485bc-d598-4409-a438-bb67d0b9413a.jpeg)

This was a photo taken by Michael after cutting the floor up and already took one of the big boards since it was too rotten.

**Comment by Dijapirzada** [comment]
![image](https://user-images.githubusercontent.com/117278179/209539707-3c890b91-0f03-4d12-b309-e2c0dc4e79ff.png)
This picutre show the end project of floor.
